name: Rust nightly check & tests

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main, master, dev, develop, '**-nightly' ]
    paths:
    - '.github/workflows/rust-nightly-check-test.yml'
    - '**/*.rs'
    - '**/Cargo.toml'
    - '**/Cargo.lock'
  pull_request:
    branches: [ main, master, dev, develop, '**-nightly' ]
    paths:
    - '.github/workflows/rust-nightly-check-test.yml'
    - '**/*.rs'
    - '**/Cargo.toml'
    - '**/Cargo.lock'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        rust: [ nightly ]
    runs-on: {% raw %}${{ matrix.os }}{% endraw %} # This fix error when cargo-generate replace variables in this file
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: {% raw %}${{ matrix.rust }}{% endraw %} # This fix error when cargo-generate replace variables in this file
        override: true
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose -- --show-output
    - name: Run ignored tests
      run: cargo test --verbose -- --show-output --ignored
